version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - path: .
      editable: true

sphinx:
  configuration: docs/conf.py
