name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Python 3.8 with matplotlib 3.6 to 3.9
          - python-version: "3.8"
            matplotlib-version: "3.6"
          - python-version: "3.8"
            matplotlib-version: "3.7"
          - python-version: "3.9"
            matplotlib-version: "3.7"
          - python-version: "3.9"
            matplotlib-version: "3.8"
          - python-version: "3.9"
            matplotlib-version: "3.9"
          - python-version: "3.10"
            matplotlib-version: "3.7"
          - python-version: "3.10"
            matplotlib-version: "3.8"
          - python-version: "3.10"
            matplotlib-version: "3.9"
          - python-version: "3.10"
            matplotlib-version: "3.10"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "matplotlib==${{ matrix.matplotlib-version }}.*"
        pip install .
        pip install pytest

    - name: Run tests
      run: pytest
