name: Tox Matrix Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tox-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install tox
      run: pip install tox

    - name: Run tox (only for this Python version's environments)
      env:
        TOXENV: py${{ matrix.python-version // 1 }}  # e.g., py38, py39
      run: |
        # List envs, filter for this Python version, run them
        python -c "import subprocess;
envs = subprocess.check_output(['tox', '-l']).decode().splitlines();
match = [e for e in envs if e.startswith('py${{ matrix.python-version | replace('.', '') }}')];
exit(subprocess.call(['tox', '-e'] + match))"
